# Default configuration of Applanix
ip: 192.168.53.100
include_raw: false
control: true
com_ports: [
  { baud: 115200, input: "BASE_1_GNSS", output: "NMEA" },
  { baud: 115200, input: "BASE_2_GNSS", output: "NMEA" },
  { baud: 115200, input: "GNSS_1", output: "GNSS_1" },
  ]

geometry:
  imu_lever_arm: { x: 0, y: 0, z: 0}
  primary_gnss_lever_arm: {x: -0.2159, y: -1.2138, z: -0.0195}
  # primary_gnss_lever_arm: {x: -0.2159, y: 1.2138, z: -0.0195}
  # primary_gnss_lever_arm: {x: -0.2159, y: 0.9075, z: -0.0195} best

  ref_mounting_angle: {x: 0, y: 0, z: 0}
  imu_mounting_angle: {x: 0, y: 0, z: 0}

gams_params:
  antenna_separation: 2.1209
  baseline_vector: { x: 0, y:  2.1209, z: 0}
  max_heading_error_rms: 3.0

dmi_params:
  dmi_scale_factor: 1324
  dmi_lever_arm: {x: -3.940, y: -1.0869, z: 3.2561}

rate: 100
